// Generated by dts-bundle v0.7.3
// Dependencies for this module:
//   ../../react
//   ../../redux
//   ../../@brightsign/bsdatamodel
//   ../../@brightsign/ba-context-model
//   ../../@brightsign/assetpool
//   ../../@brightsign/bscore

import * as React from 'react';
import { Action, Dispatch, ActionCreator } from 'redux';
import { Reducer } from 'redux';
import { DmState } from '@brightsign/bsdatamodel';
import { BaContextModelState } from '@brightsign/ba-context-model';
import { Asset } from '@brightsign/assetpool';
import { BsDmId } from '@brightsign/bsdatamodel';
import { DataFeedUsageType } from '@brightsign/bscore';
import { BsAssetLocator } from '@brightsign/bscore';

/** @module Controller:index */

/** @module Model:index */

/** @module Selector:index */

/** @module Types:index */

/** @internal */
export interface TemplateProps {
    color: BsUiModelTemplatePropertyColorState;
    onInitModel: () => any;
    onResetModel: () => any;
    onUpdateTemplateColorAsync: () => any;
    onUpdateTemplateColorBatch: () => any;
}
export class TemplateComponent extends React.Component<TemplateProps> {
    componentDidMount(): void;
    componentWillUnmount(): void;
    renderComponent(): JSX.Element;
    renderModel(): JSX.Element;
    renderController(): JSX.Element;
    renderType(): JSX.Element;
    renderError(): JSX.Element;
    renderJavaScript(): JSX.Element;
    renderBrightSignObject(): JSX.Element;
    renderHeader(): JSX.Element;
    renderBody(): JSX.Element;
    render(): JSX.Element;
}
export const Template: import("react-redux").ConnectedComponent<typeof TemplateComponent, Pick<React.ClassAttributes<TemplateComponent> & TemplateProps, "ref" | "key">>;

export const initModel: () => (dispatch: any) => Promise<any>;
export const resetModel: () => (dispatch: any) => any;

/** @private */
export const updateTemplateColorAsync: () => (dispatch: any) => Promise<any>;
/** @private */
export const updateTemplateColorBatch: () => (dispatch: any) => any;

/** @module Model:base */
/** @private */
export const BSUIMODEL_BATCH = "BSUIMODEL_BATCH";
/** @private */
export const BSUIMODEL_REHYDRATE = "BSUIMODEL_REHYDRATE";
/** @private */
export const BSUIMODEL_RESET = "BSUIMODEL_RESET";
/** @private */
export type BsUiModelDispatch = Dispatch<any>;
/** @private */
export interface BsUiModelBaseAction extends Action {
    type: string;
    payload: {};
    error?: boolean;
    meta?: {};
}
/** @private */
export interface BsUiModelAction<T> extends BsUiModelBaseAction {
    payload: T;
}
/** @private */
export type BsUiModelActionCreator<T> = ActionCreator<BsUiModelAction<T>>;
/** @private */
export type BsUiModelThunkAction<T> = (dispatch: BsUiModelDispatch, getState: () => BsUiModelState, extraArgument: undefined) => T;
/** @private */
export const bsUiModelBatchAction: (action: BsUiModelBaseAction[]) => BsUiModelBatchAction;
/** @private */
export interface BsUiModelBatchAction extends Action {
    type: string;
    payload: BsUiModelBaseAction[];
}
/** @private */
export interface RehydrateBsUiModelParams {
    newBsUiModelState: BsUiModelState;
}
/** @private */
export type RehydrateBsUiModelAction = BsUiModelAction<RehydrateBsUiModelParams>;
export const bsUiModelRehydrateModel: (bsUiModelState: BsUiModelState) => RehydrateBsUiModelAction;
/** @private */
export type ResetBsUiModelAction = BsUiModelAction<null>;
export const bsUiModelResetModel: () => ResetBsUiModelAction;
/** @private */
export interface BsPpModelBaseAction extends Action {
    type: string;
    payload: {} | null;
    error?: boolean;
    meta?: {};
}
/** @private */
export interface BsPpModelAction<T> extends BsPpModelBaseAction {
    payload: T;
}
/** @private */
export type BsPpModelActionCreator<T> = ActionCreator<BsPpModelAction<T>>;
export type BsPpModelThunkAction<T> = (dispatch: BsPpDispatch, getState: () => BsPpModelState, extraArgument: undefined) => T;
export interface BsPpBaseAction extends Action {
    type: string;
    payload: {} | null;
    error?: boolean;
    meta?: {};
}
export interface BsPpAction<T> extends BsPpBaseAction {
    payload: T;
}
export type BsPpDispatch = Dispatch<BsPpState>;
export type BsPpVoidThunkAction = any;
export type BsPpStringThunkAction = any;
export type BsPpVoidPromiseThunkAction = any;
export type BsPpThunkAction<T> = any;
export type BsPpAnyPromiseThunkAction = any;
export type BsPpActionCreator<T> = ActionCreator<BsPpAction<T>>;
export interface BsPpModelBatchAction extends Action {
    type: string;
    payload: BsPpBaseAction[];
}

/** @module Model:base */
export type BsUiReducer = Reducer<BsUiModelState>;
export const bsUiModelReducer: BsUiReducer;
export const isValidBsUiModelState: (state: any) => boolean;
export const isValidBsUiModelStateShallow: (state: any) => boolean;

export const ADD_DATA_FEED = "ADD_DATA_FEED";
export function addDataFeed(dataFeedId: string, arDataFeed: ArDataFeed): {
    type: string;
    payload: {
        dataFeedId: string;
        arDataFeed: ArDataFeed;
    };
};
export const dataFeedReducer: (state: ArDataFeedMap | undefined, action: any) => ArDataFeedMap;
/** @private */
export const isValidDataFeedState: (state: any) => boolean;

/** @module Model:template */
export const ADD_HSM: string;
export const UPDATE_HSM_PROPERTIES: string;
export const SET_HSM_TOP: string;
export const SET_HSM_INITIALIZED: string;
export const ADD_HSTATE = "ADD_HSTATE";
export const SET_MEDIA_H_STATE_TIMEOUT_ID = "SET_MEDIA_H_STATE_TIMEOUT_ID";
export const SET_MEDIA_H_STATE_PARAMETER_DATA = "SET_MEDIA_H_STATE_PARAMETER_DATA";
export const SET_ACTIVE_HSTATE = "SET_ACTIVE_HSTATE";
export const QUEUE_HSM_EVENT = "QUEUE_HSM_EVENT";
export const DEQUEUE_HSM_EVENT = "DEQUEUE_HSM_EVENT";
export type AddHsmAction = BsPpAction<Partial<Hsm>>;
export function addHsm(hsm: Hsm): AddHsmAction;
export interface HsmParams {
    id: string;
    zoneId?: string;
    x?: number;
    y?: number;
    width?: number;
    height?: number;
    initialMediaStateId?: string;
    mediaStateIdToHState?: LUT;
}
export type UpdateHsmPropertiesAction = BsPpAction<HsmParams>;
export function updateHsmProperties(params: HsmParams): UpdateHsmPropertiesAction;
export type SetHsmTopAction = BsPpAction<{}>;
export function setHsmTop(hsmId: string, topStateId: string): SetHsmTopAction;
export type SetHsmInitializedAction = BsPpAction<Partial<Hsm>>;
export function setHsmInitialized(id: string, initialized: boolean): SetHsmInitializedAction;
export type SetActiveHStateAction = BsPpAction<HState | null | any>;
export function setActiveHState(hsmId: string, activeState: HState | null): SetActiveHStateAction;
export type AddHStateAction = BsPpAction<{
    id: string;
    type: HStateType;
    hsmId: string;
    superStateId: string;
    name: string;
    data?: MediaHStateData | null;
}>;
export function addHState(id: string, hStateSpecification: HStateSpecification, data?: MediaHStateData | null): AddHStateAction;
export function setMediaHStateTimeoutId(hStateId: string, timeoutId: number): any;
export function setMediaHStateParameter(hStateId: string, parameterName: string, parameterValue: any): any;
export type HsmEventAction = BsPpAction<HsmEventType>;
export function queueHsmEvent(event: HsmEventType): HsmEventAction;
export function dequeueHsmEvent(): BsPpBaseAction;
export const hsmReducer: import("redux").Reducer<import("redux").CombinedState<HsmState>, import("redux").AnyAction>;
/** @private */
export const isValidHsmState: (state: any) => boolean;

export const SET_VIDEO_ELEMENT_REF = "SET_VIDEO_ELEMENT_REF";
export type SetPlaybackAction = BsPpAction<PlaybackState>;
export const setVideoElementRef: (videoElementRef: HTMLVideoElement | null) => SetPlaybackAction;
export const playbackDefaults: PlaybackState;
export const playbackReducer: (state: PlaybackState | undefined, { type, payload }: (SetPlaybackAction)) => PlaybackState;

export const UPDATE_PRESENTATION_DATA = "UPDATE_PRESENTATION_DATA";
export const UPDATE_RUNTIME_ENVIRONMENT = "UPDATE_RUNTIME_ENVIRONMENT";
export const UPDATE_PRESENTATION_SRC_DIRECTORY = "UPDATE_PRESENTATION_SRC_DIRECTORY";
export const UPDATE_SYNC_SPEC_FILE_MAP = "UPDATE_SYNC_SPEC_FILE_MAP";
export const UPDATE_AUTOSCHEDULE = "UPDATE_AUTOSCHEDULE";
export const UPDATE_SCREEN_DIMENSIONS = "UPDATE_SCREEN_DIMENSIONS";
export type UpdatePresentationDataAction = BsPpAction<Partial<PresentationDataState>>;
export type UpdatePresentationStringAction = BsPpAction<Partial<PresentationDataState>>;
export function updatePresentationData(presentationDataState: PresentationDataState): UpdatePresentationDataAction;
export const updateRuntimeEnvironment: (runtimeEnvironment: RuntimeEnvironment) => UpdatePresentationDataAction;
export const updatePresentationSrcDirectory: (srcDirectory: string) => UpdatePresentationDataAction;
export const updatePresentationSyncSpecFileMap: (syncSpecFileMap: SyncSpecFileMap) => UpdatePresentationDataAction;
export const updatePresentationAutoschedule: (autoSchedule: PpSchedule) => UpdatePresentationDataAction;
export const updateScreenDimensions: (screenDimensions: Dimensions) => UpdatePresentationDataAction;
export const presentationDataDefaults: PresentationDataState;
export const presentationDataReducer: (state: PresentationDataState | undefined, { type, payload }: (UpdatePresentationDataAction)) => PresentationDataState;

/** @module Model:template */
/** @private */
export const templateReducer: (state: BsUiModelTemplateState, action: BsUiModelBatchAction) => BsUiModelTemplateState;
/** @private */
export const isValidTemplateState: (state: any) => boolean;
/** @private */
export const isValidTemplateStateShallow: (state: any) => boolean;

/** @module Model:templateProperty */
/** @private */
export const BSUIMODEL_UPDATE_TEMPLATE_PROPERTY: string;
/** @private */
export const BSUIMODEL_RESET_TEMPLATE_PROPERTY: string;
/** @private */
export type UpdateTemplatePropertyAction = BsUiModelAction<Partial<BsUiModelTemplatePropertyState>>;
/** @private */
export type ResetTemplatePropertyAction = BsUiModelAction<null>;
/** @private */
export const bsUiModelResetTemplateProperty: () => ResetTemplatePropertyAction;
/** @private */
export const bsUiModelUpdateTemplateColor: (color: BsUiModelTemplatePropertyColorState) => UpdateTemplatePropertyAction;
/** @private */
export const templatePropertyDefault: BsUiModelTemplatePropertyState;
/** @private */
export const templatePropertyReducer: (state: BsUiModelTemplatePropertyState | undefined, { type, payload }: (UpdateTemplatePropertyAction | ResetTemplatePropertyAction | ResetBsUiModelAction | BsUiModelAction<RehydrateBsUiModelParams>)) => BsUiModelTemplatePropertyState;
/** @private */
export const isValidColor: (state: any) => boolean;
/** @private */
export const isValidTemplatePropertyState: (state: any) => boolean;
/** @private */
export const isValidTemplatePropertyStateShallow: (state: any) => boolean;

/** @module Selector:base */
/** @private */
export const bsUiModelFilterBaseState: (state: any) => BsUiModelState;
/** @private */
export const bsUiModelGetBaseState: (state: BsUiModelState) => BsUiModelState;

/** @module Selector:template */
/** @private */
export const bsUiModelGetTemplateState: (state: BsUiModelState) => BsUiModelTemplateState;

/** @module Selector:templateProperty */
/** @private */
export const bsUiModelGetTemplatePropertyState: (state: BsUiModelState) => BsUiModelTemplatePropertyState;
/** @private */
export const bsUiModelGetTemplatePropertyColorState: (state: BsUiModelState) => BsUiModelTemplatePropertyColorState;

/** @module Types:base */
/** @private */
export interface BsUiModelState {
    template: BsUiModelTemplateState;
}
/** @private */
export const createModel: (template: BsUiModelTemplateState) => BsUiModelState;
/** @module Types:base */
export class RuntimeEnvironment {
    static BrightSign: string;
    static BaconPreview: string;
    static Dev: string;
}
export type DeepPartial<T> = {
    [P in keyof T]?: DeepPartial<T[P]>;
};
export interface BsPpState {
    type: any;
    bsdm: DmState;
    bacdm: BaContextModelState;
    bsPlayer: BsPpModelState;
}
export interface BsPpModelState {
    hsmState: HsmState;
    presentationData: PresentationDataState;
    playback: PlaybackState;
    arDataFeeds: ArDataFeedMap;
}
export interface LUT {
    [key: string]: any;
}
export interface BsPpBaseObject {
    id: string;
}
export interface BsPpMap<T extends BsPpBaseObject> {
    [id: string]: T;
}
export interface FileLUT {
    [fileName: string]: string;
}

/** @module Types:template */
/** @private */
export interface BsUiModelTemplateState {
    readonly property: BsUiModelTemplatePropertyState;
}
/** @private */
export const createTemplate: (property: BsUiModelTemplatePropertyState) => BsUiModelTemplateState;

/** @private */
export interface BsUiModelTemplatePropertyColorState {
    a: number;
    r: number;
    g: number;
    b: number;
}
/** @private */
export interface BsUiModelTemplatePropertyState {
    color: BsUiModelTemplatePropertyColorState;
}
/** @private */
export const createTemplateProperty: (color: BsUiModelTemplatePropertyColorState) => BsUiModelTemplatePropertyState;
/** @private */
export const createBsColor: (r: number, g: number, b: number, a: number) => BsUiModelTemplatePropertyColorState;

export type HsmMap = BsPpMap<Hsm>;
export type HStateMap = BsPpMap<HState>;
export interface HsmState {
    hsmById: HsmMap;
    hStateById: HStateMap;
    hsmEventQueue: HsmEventType[];
}
export interface Hsm {
    id: string;
    name: string;
    type: HsmType;
    topStateId: string;
    activeStateId: string | null;
    initialized: boolean;
    properties: HsmProperties;
}
export type HsmProperties = ZoneHsmProperties | MediaZoneHsmProperties | {};
export interface ZoneHsmProperties {
    zoneId: string;
    x: number;
    y: number;
    width: number;
    height: number;
    initialMediaStateId: string;
}
export interface MediaZoneHsmProperties extends ZoneHsmProperties {
    mediaStateIdToHState: LUT;
}
export interface HsmEventType {
    EventType: string;
    data?: any;
    EventData?: any;
}

export class HsmType {
    static Player: string;
    static VideoOrImages: string;
}
export class HsmTimerType {
    static MediaHState: string;
    static MrssState: string;
}

export class HStateType {
    static Top: string;
    static Player: string;
    static Playing: string;
    static Waiting: string;
    static Image: string;
    static Mrss: string;
    static Video: string;
    static SuperState: string;
}
export interface HState {
    id: string;
    type: HStateType;
    hsmId: string;
    superStateId: string;
    name: string;
}
export interface MediaHState extends HState {
    data: MediaHStateData;
}
export interface MediaHStateData {
    mediaStateId: string;
    mediaStateData?: MediaHStateParamsData | null;
}
export type MediaHStateParamsData = MediaHStateCustomData;
export type MediaHStateCustomData = ImageStateData | VideoStateData | SuperStateData | MrssStateData;
export interface ImageStateData {
    timeoutId?: number;
}
export interface VideoStateData {
    timeoutId?: number;
}
export interface SuperStateData {
    timeoutId?: number;
}
export interface MrssStateData {
    timeoutId?: number;
    dataFeedId: string;
    currentFeedId: string | null;
    pendingFeedId: string | null;
    displayIndex: number;
    firstItemDisplayed: boolean;
    waitForContentTimer: any;
}
export interface HStateSpecification {
    type: HStateType;
    hsmId: string;
    superStateId: string;
    name: string;
}
export interface HSMStateData {
    nextStateId: string | null;
}

export interface ArFeed {
    rss: any;
}
export interface ArDataFeedBase {
    type: string;
    id: BsDmId;
    sourceId: BsDmId;
    usage: DataFeedUsageType;
}
export interface ArTextItem {
    articleTitle: string;
    articleDescription: string;
}
export interface ArTextFeedProperties {
    textItems: ArTextItem[];
    articlesByTitle: any;
}
export interface ArMrssItem {
    guid: string;
    link: string;
    title: string;
    pubDate: string;
    duration: string;
    fileSize: string;
    medium: string;
    type: string;
    url: string;
    filePath?: string;
}
export interface ArMrssFeedProperties {
    mrssItems: ArMrssItem[];
    title: string;
    playtime: string;
    ttl: string;
    assetList: Asset[];
}
export interface ArContentFeedItem {
    name: string;
    url: string;
    medium: string;
    hash: string;
}
export interface ArContentFeedProperties {
    contentItems: ArContentFeedItem[];
    assetList: Asset[];
}
export interface ArMediaFeedItem {
    filePath: string;
    medium: string;
}
export type ArDataFeed = ArTextFeed | ArMrssFeed | ArContentFeed;
export type ArTextFeed = ArDataFeedBase & ArTextFeedProperties;
export type ArMrssFeed = ArDataFeedBase & ArMrssFeedProperties;
export type ArContentFeed = ArDataFeedBase & ArContentFeedProperties;
export interface ArDataFeedMap {
    [dataFeedId: string]: ArDataFeed;
}

export interface PlaybackState {
    videoElementRef: HTMLVideoElement | null;
}

export interface PresentationDataState {
    runtimeEnvironment: RuntimeEnvironment;
    screenDimensions: Dimensions;
    srcDirectory: string;
    syncSpecFileMap: SyncSpecFileMap | null;
    autoSchedule: PpSchedule | null;
}
export interface SyncSpecFileMap {
    [name: string]: SyncSpecDownload;
}
export interface SyncSpecDownload {
    name: string;
    hash: SyncSpecHash;
    size: number;
    link: string;
}
interface SyncSpecHash {
    method: string;
    hex: string;
}
interface SyncSpecMeta {
    client: any;
    server: any;
}
export interface RawSyncSpecFiles {
    download: SyncSpecDownload[];
    ignore: any;
    delete: any;
}
export interface RawSyncSpec {
    meta: SyncSpecMeta;
    files: RawSyncSpecFiles;
}
export {};

export interface PpSchedule {
    scheduledPresentations: ScheduledPresentation[];
}
export interface ScheduledPresentation {
    presentationToSchedule: ScheduledPresentationFileData;
    presentationLocator: BsAssetLocator;
    dateTime: string;
    duration: number;
    allDayEveryDay: boolean;
    recurrence: boolean;
    recurrencePattern: string;
    recurrencePatternDaily: string;
    recurrencePatternDaysOfWeek: number;
    recurrenceStartDate: string;
    recurrenceGoesForever: boolean;
    recurrenceEndDate: string;
    interruption: boolean;
}
export interface ScheduledPresentationFileData {
    name: string;
    fileName: string;
    filePath: string;
}

export enum BsUiErrorType {
    unknownError = 0,
    unexpectedError = 1,
    invalidParameters = 2,
    invalidOperation = 3,
    apiError = 4,
    invalidModel = 5
}
export class BsUiError extends Error {
    name: string;
    type: BsUiErrorType;
    constructor(type: BsUiErrorType, reason?: string);
}
export function isBsUiError(error: Error): error is BsUiError;

export const newBsPpId: () => string;
export interface Dimensions {
    width: number;
    height: number;
}
export const calculateAspectRatioFit: (srcWidth: number, srcHeight: number, maxWidth: number, maxHeight: number) => Dimensions;

